spring.application.name=UserValidationCheck

spring.datasource.url=jdbc:postgresql://localhost:5432/UserDetails
spring.datasource.username=postgres
spring.datasource.password=Sindhu@1234

spring.jpa.hibernate.ddl-auto=update

